# Generated by Django 5.0.1 on 2024-02-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('club', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(choices=[('Academic ', 'Academic '), ('Cultural ', 'Cultural '), ('Social ', 'Social '), ('Sports  ', 'Sports  ')], max_length=200, null=True)),
                ('time', models.TimeField(null=True)),
                ('venue', models.CharField(max_length=200, null=True)),
                ('team_size', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('date_event', models.DateField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_free', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='regEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], max_length=200, null=True)),
            ],
        ),
    ]
