# Generated by Django 5.0.1 on 2024-02-06 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_events_regevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='regevents',
            name='Events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.events'),
        ),
        migrations.AddField(
            model_name='regevents',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.user'),
        ),
    ]
