# Generated by Django 5.0.1 on 2024-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_tag_regevents_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regevents',
            name='tags',
        ),
        migrations.AddField(
            model_name='events',
            name='tags',
            field=models.ManyToManyField(to='events.tag'),
        ),
    ]
