# Generated by Django 5.0.1 on 2024-02-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_regevents_note_alter_events_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regevents',
            name='note',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
