# Generated by Django 5.0.1 on 2024-02-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
