# Generated by Django 5.0.1 on 2024-02-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_remove_user_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
