# Generated by Django 5.0.1 on 2024-02-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_customuser_remove_events_poster'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
