# Generated by Django 5.0.1 on 2024-03-03 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_regevents_user_userevent_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='profile_pic',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pic'),
            preserve_default=False,
        ),
    ]
