# Generated by Django 5.0.1 on 2024-03-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_events_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='club',
            field=models.CharField(choices=[('Spectrum', 'Spectrum'), ('La Fiesta', 'La Fiesta'), ('Coffee', 'Coffee'), ('Arista', 'Arista'), ('Xpressions', 'Xpressions'), ('Prakrthi', 'Prakrthi')], max_length=200, null=True),
        ),
    ]
