# Generated by Django 5.0.1 on 2024-03-11 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_partcipateevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partcipateevent',
            name='name',
        ),
        migrations.AddField(
            model_name='partcipateevent',
            name='event_name',
            field=models.ForeignKey(db_column='name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.events'),
        ),
        migrations.AlterField(
            model_name='partcipateevent',
            name='team_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
