# Generated by Django 5.0.1 on 2024-03-11 18:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_remove_partcipateevent_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='partcipateEvent',
            new_name='partcipateEvents',
        ),
    ]
